apiVersion: ceph.rook.io/v1
kind: Filesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  # The metadata pool spec
  metadataPool:
    replicated:
      # Increase the replication size if you have more than one osd
      size: 1
  # The list of data pool specs
  dataPools:
    - failureDomain: osd
      replicated:
        size: 1
  metadataServer:
    activeCount: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: NFS
provisioner: ceph.rook.io/filesystem
parameters:
  fsName: myFS # Name of the filesystem to use.
