---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ichbinroot
spec:
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  hostNetwork: true
  hostPID:     true
  volumes:
  - '*'


