
kind: ClusterRole
apiVersion:  rbac.authorization.k8s.io/v1
metadata:
  name:   "psp:ichbinroot"
rules: 
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - ichbinroot
---

kind:        ClusterRoleBinding
apiVersion:  rbac.authorization.k8s.io/v1
metadata:
  name:      psp:ichbinroot
roleRef:
  kind:      ClusterRole
  name:      "psp:ichbinroot"
  apiGroup:  rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters

