apiVersion: batch/v1
kind: CronJob
metadata:
  name: blender
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 0   
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: alpine
            command: ["/bin/sh","-c", "echo hallo"]
          restartPolicy: OnFailure
