apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwlimitted
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: wwwlimitted
  template:
    metadata:
      name: wwwlimitted
      labels:
        app: wwwlimitted
    spec:
      containers:
      - name: image1
        image: erkules/nginxhostname
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 10m
            memory: 20Mi
