apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentprobe
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: internal
  template:
    metadata:
      name: www
      labels:
        app: internal
    spec:
      containers:
      - name: image1
        image: erkules/nginxhostname:v1
        #readinessProbe:
        #  exec:
        #    command:
        #    - cat
        #    - /etc/issue
