apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwuser
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: wwwuser
  template:
    metadata:
      name: wwwuser
      labels:
        app: wwwuser
    spec:
      containers:
      - name: image1
        image: erkules/nginxhostnameuser
