apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwuser
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: wwwuser
  template:
    metadata:
      name: wwwuser
      labels:
        app: wwwuser
    spec:
      containers:
      - name: image1
        image: erkules/nginxhostnameuser:v1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: wwwuser
spec: 
  selector:
    app: wwwuser
  ports:
  - port: 8080

---

# Bis K8s 1.18
apiVersion: networking.k8s.io/v1beta1
kind:       Ingress
metadata:
  name: lalaal
spec:
  rules:
  - host: YOURNAMESPACE.erkmerk.de
    http:
      paths:
      - path: /
        backend:
          serviceName:  wwwuser
          servicePort:  8080

