apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwanti
spec:
  replicas: 9
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wwwanti
  template:
    metadata:
      name: wwwanti
      labels:
        app: wwwanti
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:

          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - wwwanti
              topologyKey: kubernetes.io/hostname
      containers:
      - name: image1
        image: erkules/nginxhostname:v1

