apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 4
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      name: www
      labels:
        app: www
    spec:
      containers:
      - name: image1
        image: erkules/nginxhostname
        ports:
        - containerPort: 80
