
apiVersion: v1
kind: Service
metadata:
  name: probe
spec: 
  selector:
    app: probe
  ports:
  - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentprobe
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      name: www
      labels:
        app: probe
    spec:
      containers:
      - name: web
        image: erkules/nginxhostname:v1
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/issue
          periodSeconds: 1 
          failureThreshold: 1
        livenessProbe:
          exec:
            command:
            - cat
            - /usr/share/nginx/html/index.html
          periodSeconds: 1 
          failureThreshold: 1
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/letsgo
          # Wir warten bis zu 150 Sekunden
          failureThreshold: 30
          periodSeconds: 5 
