
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      name: registry
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
      - name: webui
        image: hyper/docker-registry-web
        env:
          - name: REGISTRY_NAME
            value: localhost:5000
          - name: REGISTRY_URL
            value: http://registry:5000/v2


---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  ports:
  - port: 5000
    name: registry
  - port: 8080
    name: webui
  selector:
    app: registry
---

apiVersion: networking.k8s.io/v1beta1
kind:       Ingress
metadata:
  name: registry
  namespace: registry
spec:
  rules:
  - host: registry.bla
    http:
      paths:
      - path: /
        backend:
          serviceName:  registry
          servicePort:  5000

