---
# tasks file for Ihateansible
- name: build Ihateansible 
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: ihateansible
        template:
          metadata:
            labels:
              app: ihateansible
          spec:
            containers:
            - name: haha
              image: "erkules/nginxhostname" 
              imagePullPolicy: Always
