---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
---
kind:        ClusterRole
apiVersion:  rbac.authorization.k8s.io/v1
metadata:
  name:      default
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - default

---

kind:        ClusterRoleBinding
apiVersion:  rbac.authorization.k8s.io/v1
metadata:
  name:      defaultns
roleRef:
  kind:      ClusterRole
  name:      default
  apiGroup:  rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
