
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "morecomplex.fullname" . }}-pre-install
  labels:
{{ include "morecomplex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  containers:
    - name: wget
      image: erkules/kubectl:v1.16.2
      command: 
      - sh
      - -c 
      - " echo pre-install && sleep 10 "
  restartPolicy: Never
---
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "morecomplex.fullname" . }}-post-install
  labels:
{{ include "morecomplex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  containers:
    - name: wget
      image: erkules/kubectl:v1.16.2
      command: 
      - sh
      - -c 
      - " echo post-install && sleep 10 "
  restartPolicy: Never
---




---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "morecomplex.fullname" . }}-pre-delete
  labels:
{{ include "morecomplex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
spec:
  containers:
    - name: wget
      image: erkules/kubectl:v1.16.2
      command: 
      - sh
      - -c 
      - " echo pre-delete && sleep 10 "
  restartPolicy: Never
---
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "morecomplex.fullname" . }}-post-delete
  labels:
{{ include "morecomplex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
spec:
  containers:
    - name: wget
      image: erkules/kubectl:v1.16.2
      command: 
      - sh
      - -c 
      - " echo post-delete && sleep 10 "
  restartPolicy: Never
---



---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "morecomplex.fullname" . }}-pre-upgrade
  labels:
{{ include "morecomplex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  containers:
    - name: wget
      image: erkules/kubectl:v1.16.2
      command: 
      - sh
      - -c 
      - " echo pre-upgrade && sleep 10 "
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "morecomplex.fullname" . }}-post-upgrade
  labels:
{{ include "morecomplex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade
spec:
  containers:
    - name: wget
      image: erkules/kubectl:v1.16.2
      command: 
      - sh
      - -c 
      - " echo post-upgrade && sleep 10 "
  restartPolicy: Never
---
