# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventinghallo
spec:
  template:
    metadata:
      name: eventinghallo-v1
    spec:
      containers:
      - image: quay.io/rhdevelopers/eventinghello:0.0.2
