apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-sa
  namespace: serverless

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-watcher
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-ra-event-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-watcher
subjects:
- kind: ServiceAccount
  name: events-sa
  namespace: serverless

---
#apiVersion: sources.knative.dev/v1
apiVersion: sources.knative.dev/v1beta1
kind: ApiServerSource
metadata:
  name: testevents
  namespace: serverless
spec:
  serviceAccountName: events-sa
  mode: Resource
  resources:
  - apiVersion: v1
    kind: Event
  sink:
    ref:
      #apiVersion: eventing.knative.dev/v1
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: testevents-trigger
  namespace: serverless
spec:
  broker: serverless
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

---

# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: serverless
spec:
  template:
    spec:
      containers:
      - # This corresponds to
        # https://github.com/knative/eventing-contrib/tree/master/cmd/event_display/main.go
        image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
