apiVersion: sources.knative.dev/v1beta1
kind: PingSource
metadata:
  name: eventinghallo-ping-source
spec:
  schedule: "*/2 * * * *"
  jsonData: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghallo
