apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: display
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
--- 
apiVersion: sources.knative.dev/v1beta1
kind: PingSource
metadata:
  name: ksvc-ping-source
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: display
    #uri:  http://display.serverless.example.com
