---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
    # The root route on which each incoming alert enters.
    route:
      group_by: ['alertname', 'instance']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h 
      receiver: default
      routes:
      - match_re:
          service: ^(foo1|foo2|baz)$
        receiver: default
        routes:
        - match:
            severity: critical
          receiver: default
      - match:
          service: files
        receiver: default
        routes:
        - match:
            severity: critical
          receiver: default
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname', 'cluster', 'service']
    receivers:
    - name: default
      webhook_configs:
      - send_resolved: false
        url: https://chat.reisenden.info/hooks/xwwfGXfgS6JD4qM3i/2EByxqvFmk3uFtbH2CxtiWArzvq3oiJQvg7oyvcHYLhESbWR
