apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busyboxeporter
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: erkan_queue_length
      target:
        type: AverageValue
        averageValue: 5
