apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: safe
  template:
    metadata:
      name: safe
      labels:
        app: safe
    spec:
      terminationGracePeriodSeconds: 2
      nodeSelector:
        kubernetes.io/hostname: erkan1
      containers:
      - name: bench
        image: jess/stress
        args: ["--vm","1","--vm-bytes","200m","--vm-hang","0"]
        resources:
          requests:
            memory: 250Mi
