apiVersion: v1
kind: Namespace
metadata:
  name: donquota
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: donquota
spec:
  hard:
    pods: 4
    configmaps: 5
    services: 2
    count/deployments.apps: 2
    limits.cpu: 1
    limits.memory: 2Gi
    requests.cpu: 1
    requests.memory: 1Gi
    persistentvolumeclaims: 2
    default.storageclass.storage.k8s.io/requests.storage: 500Gi
---
