apiVersion: v1
kind: Namespace
metadata:
  name: scoped
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: scopedpc
value: 10000
globalDefault: false
description: "nur mal zeigen das scoped geht"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scopedquota
  namespace: scoped
spec:
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: 
      - scopedpc
  hard:
    pods: 10
---
