apiVersion: v1
kind: Pod
metadata:
  name: gimmesecret
spec:
  terminationGracePeriodSeconds: 2
  serviceAccountName: sa2vault
  volumes:
  - name: geheim
    csi:
      driver:  secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: vault

  containers:
  - name: will
    volumeMounts:
    - name: geheim
      mountPath: /secret
      readOnly: true
    image: alpine
    command:
    - sleep
    - "5000"

