apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: erkans.linsenraum.de
spec:
  group: linsenraum.de
  # list of versions supported by this CustomResourceDefinition
  versions:
  - name: v1alpha1
    served: true
    storage: true
    #    schema:
    #      openAPIV3Schema:
    #        type: object
    #        properties:
    #          blabla:
    #            type: string
  # The conversion section is introduced in Kubernetes 1.13+ with a default value of
  # None conversion (strategy sub-field set to None).
  conversion:
    # None conversion assumes the same schema for all versions and only sets the apiVersion
    # field of custom resources to the proper value
    strategy: None
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    plural: erkans
    # singular name to be used as an alias on the CLI and for display
    singular: erkan
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Erkan
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - er
