kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetescamp
subjects:
- kind: User
  name: hallo
roleRef:
  kind: Role
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
