kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kubernetescamp
subjects:
- kind: Group
  name: system:authenticated
roleRef:
  kind: Role
  name: heapster-service-proxy
  apiGroup: rbac.authorization.k8s.io

