apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdukannstmichmal
spec:
  crd:
    spec:
      names:
        kind: K8sDuKannstMichMal
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdukannstmichmal 

        violation[{"msg": msg}] {
          msg := "Du kannst mich mal"  
        }
