#---
#kind: Namespace
#apiVersion: v1
#metadata:
#  name: serverless
---
kind: Service
apiVersion: serving.knative.dev/v1alpha1
metadata:
  name: www
spec:
  template:
    metadata:
      name: www-v2
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
        env:
        - name: TARGET
          value: hahav2
  traffic:
  - revisionName: www-v2
    percent: 10
  - revisionName: www-v1
    percent: 90

