apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls-prod
spec:
  DELETEME
  secretName: harborerkanzwerkorgprod
  dnsNames:
  - "harbor.erkan.zwerk.org"
  issuerRef:
    name: le-clusterissuer-prod
    kind: ClusterIssuer
