apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls-staging
spec:
  DELETEME
  secretName: harborerkanzwerkorgstaging
  dnsNames:
  - "harbor.erkan.zwerk.org"
  issuerRef:
    name: le-clusterissuer-staging
    kind: ClusterIssuer
