apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notary-tls-staging
spec:
  DELETEME
  secretName: notaryerkanzwerkorgstaging
  dnsNames:
  - "notary.erkan.zwerk.org"
  issuerRef:
    name: le-clusterissuer-staging
    kind: ClusterIssuer
