apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notary-tls-prod
spec:
  DELETEME
  secretName: notaryerkanzwerkorgprod
  dnsNames:
  - "notary.erkan.zwerk.org"
  issuerRef:
    name: le-clusterissuer-prod
    kind: ClusterIssuer
