apiVersion: v1
kind: Pod
metadata:
  name: pod-ressources-stress
spec:
  containers:
  - name: stress
    image: jess/stress
    command:
    - sleep
    - "5000"
    resources:
      requests:
        cpu: 10m
        memory: 100M
        ephemeral-storage: "1Gi"
      limits:
        cpu: 10m
        memory: 1000M
        ephemeral-storage: "1Gi"
       
# stress  -m 128m --name cg jess/stress --vm 1 --vm-bytes 100m --vm-hang 0
