apiVersion: v1
kind: Pod
metadata:
  name: pod-resources
spec:
  containers:
  - name: meinserver
    image: erkules/nginxhostname
    resources:
      requests:
        cpu: 10m
        memory: 100M
      limits:
        cpu: 10m
        memory: 1000M
       

