apiVersion: v1
kind: Pod
metadata:
  name: www-liveness
spec:
  containers:
  - name: meinserver
    image: erkules/nginxhostname
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - cat 
        - /etc/issue
      timeoutSeconds: 1
      initialDelaySeconds: 5

