apiVersion: v1
kind: Pod
metadata:
  name: www-liveness
spec:
  containers:
  - name: meinserver
    image: erkules/nginxhostname
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /
        port: 80
      timeoutSeconds: 1
      initialDelaySeconds: 5

