apiVersion: v1
kind: ConfigMap
metadata:
  name: conni
data:
  hallo: welt 
  key: |-
   hhhh
   hhhh
   hhhh
   hhhh
---
apiVersion: v1
kind: Pod
metadata:
  name: conni
spec:
  containers:
  - name: jaja
    image: alpine
    env:
    - name: ENVI
      valueFrom: 
        configMapKeyRef:
          name: conni
          key: hallo
    command:
    - echo
    - $(ENVI)
    imagePullPolicy: IfNotPresent

