apiVersion: v1
kind: ConfigMap
metadata:
  name: index
data:
  index.html: |
    <h1>hallo</h1>
    <loetkolben>
    aua
    </loetkolben>
  mama.html: |
    eine
    schoene
    neue
    welt


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 4
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      name: www
      labels:
        app: www
    spec:
      containers:
      - name: image1
        image: erkules/nginxhostname
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: website
          mountPath: /var/www
        imagePullPolicy: IfNotPresent
      volumes:
      - name: website
        configMap:
          name: index

