apiVersion: v1
kind: Pod   
metadata:   
  name: secret-env-pod
spec:       
  containers:
  - image: busybox     
    name: busymussi
    command:
    - sleep 
    - "4000"
    env:
    - name: HOBBY
      valueFrom:
        secretKeyRef:
          name: geheimnis
          key: hobby

