apiVersion: v1
kind: Pod   
metadata:   
  name: secret-pod
spec:       
  containers:
  - image: busybox                                                                                   
    name: busymussi
    command:
    - sleep 
    - "4000"
    volumeMounts:
      - name: secret
        readOnly: true
        mountPath: /tmp
  volumes:  
  - name: secret
    secret: 
      secretName: geheimnis

